export default {
  "gregorian": "2026-10-06",
  "weekday": "Tuesday",
  "sections": {
    "chumash": {
      "parsha": "Bereshit",
      "aliyah": "Shlishi",
      "ref": "Genesis 2:20-3:21",
      "link": "https://www.sefaria.org/Genesis_2%3A20-3%3A21",
      "chabad": "https://www.chabad.org/dailystudy/torahreading.asp?tdate=10/6/2026",
      "text": {
        "ref": "Genesis 2:20-3:21",
        "he": [
          "וַיִּקְרָ֨א הָֽאָדָ֜ם שֵׁמ֗וֹת לְכׇל־הַבְּהֵמָה֙ וּלְע֣וֹף הַשָּׁמַ֔יִם וּלְכֹ֖ל חַיַּ֣ת הַשָּׂדֶ֑ה וּלְאָדָ֕ם לֹֽא־מָצָ֥א עֵ֖זֶר כְּנֶגְדּֽוֹ׃",
          "וַיַּפֵּל֩ יְהֹוָ֨ה אֱלֹהִ֧ים&thinsp;׀&thinsp;תַּרְדֵּמָ֛ה עַל־הָאָדָ֖ם וַיִּישָׁ֑ן וַיִּקַּ֗ח אַחַת֙ מִצַּלְעֹתָ֔יו וַיִּסְגֹּ֥ר בָּשָׂ֖ר תַּחְתֶּֽנָּה׃",
          "וַיִּ֩בֶן֩ יְהֹוָ֨ה אֱלֹהִ֧ים&thinsp;׀&thinsp;אֶֽת־הַצֵּלָ֛ע אֲשֶׁר־לָקַ֥ח מִן־הָֽאָדָ֖ם לְאִשָּׁ֑ה וַיְבִאֶ֖הָ אֶל־הָֽאָדָֽם׃",
          "וַיֹּ֘אמֶר֮ הָֽאָדָם֒ זֹ֣את הַפַּ֗עַם עֶ֚צֶם מֵֽעֲצָמַ֔י וּבָשָׂ֖ר מִבְּשָׂרִ֑י לְזֹאת֙ יִקָּרֵ֣א אִשָּׁ֔ה כִּ֥י מֵאִ֖ישׁ לֻֽקְחָה־זֹּֽאת׃",
          "עַל־כֵּן֙ יַֽעֲזׇב־אִ֔ישׁ אֶת־אָבִ֖יו וְאֶת־אִמּ֑וֹ וְדָבַ֣ק בְּאִשְׁתּ֔וֹ וְהָי֖וּ לְבָשָׂ֥ר אֶחָֽד׃",
          "וַיִּֽהְי֤וּ שְׁנֵיהֶם֙ עֲרוּמִּ֔ים הָֽאָדָ֖ם וְאִשְׁתּ֑וֹ וְלֹ֖א יִתְבֹּשָֽׁשׁוּ׃",
          "וְהַנָּחָשׁ֙ הָיָ֣ה עָר֔וּם מִכֹּל֙ חַיַּ֣ת הַשָּׂדֶ֔ה אֲשֶׁ֥ר עָשָׂ֖ה יְהֹוָ֣ה אֱלֹהִ֑ים וַיֹּ֙אמֶר֙ אֶל־הָ֣אִשָּׁ֔ה אַ֚ף כִּֽי־אָמַ֣ר אֱלֹהִ֔ים לֹ֣א תֹֽאכְל֔וּ מִכֹּ֖ל עֵ֥ץ הַגָּֽן׃",
          "וַתֹּ֥אמֶר הָֽאִשָּׁ֖ה אֶל־הַנָּחָ֑שׁ מִפְּרִ֥י עֵֽץ־הַגָּ֖ן נֹאכֵֽל׃",
          "וּמִפְּרִ֣י הָעֵץ֮ אֲשֶׁ֣ר בְּתוֹךְ־הַגָּן֒ אָמַ֣ר אֱלֹהִ֗ים לֹ֤א תֹֽאכְלוּ֙ מִמֶּ֔נּוּ וְלֹ֥א תִגְּע֖וּ בּ֑וֹ פֶּן־תְּמֻתֽוּן׃",
          "וַיֹּ֥אמֶר הַנָּחָ֖שׁ אֶל־הָֽאִשָּׁ֑ה לֹֽא־מ֖וֹת תְּמֻתֽוּן׃",
          "כִּ֚י יֹדֵ֣עַ אֱלֹהִ֔ים כִּ֗י בְּיוֹם֙ אֲכׇלְכֶ֣ם מִמֶּ֔נּוּ וְנִפְקְח֖וּ עֵֽינֵיכֶ֑ם וִהְיִיתֶם֙ כֵּֽאלֹהִ֔ים יֹדְעֵ֖י ט֥וֹב וָרָֽע׃",
          "וַתֵּ֣רֶא הָֽאִשָּׁ֡ה כִּ֣י טוֹב֩ הָעֵ֨ץ לְמַאֲכָ֜ל וְכִ֧י תַֽאֲוָה־ה֣וּא לָעֵינַ֗יִם וְנֶחְמָ֤ד הָעֵץ֙ לְהַשְׂכִּ֔יל וַתִּקַּ֥ח מִפִּרְי֖וֹ וַתֹּאכַ֑ל וַתִּתֵּ֧ן גַּם־לְאִישָׁ֛הּ עִמָּ֖הּ וַיֹּאכַֽל׃",
          "וַתִּפָּקַ֙חְנָה֙ עֵינֵ֣י שְׁנֵיהֶ֔ם וַיֵּ֣דְע֔וּ כִּ֥י עֵֽירֻמִּ֖ם הֵ֑ם וַֽיִּתְפְּרוּ֙ עֲלֵ֣ה תְאֵנָ֔ה וַיַּעֲשׂ֥וּ לָהֶ֖ם חֲגֹרֹֽת׃",
          "וַֽיִּשְׁמְע֞וּ אֶת־ק֨וֹל יְהֹוָ֧ה אֱלֹהִ֛ים מִתְהַלֵּ֥ךְ בַּגָּ֖ן לְר֣וּחַ הַיּ֑וֹם וַיִּתְחַבֵּ֨א הָֽאָדָ֜ם וְאִשְׁתּ֗וֹ מִפְּנֵי֙ יְהֹוָ֣ה אֱלֹהִ֔ים בְּת֖וֹךְ עֵ֥ץ הַגָּֽן׃",
          "וַיִּקְרָ֛א יְהֹוָ֥ה אֱלֹהִ֖ים אֶל־הָֽאָדָ֑ם וַיֹּ֥אמֶר ל֖וֹ אַיֶּֽכָּה׃",
          "וַיֹּ֕אמֶר אֶת־קֹלְךָ֥ שָׁמַ֖עְתִּי בַּגָּ֑ן וָאִירָ֛א כִּֽי־עֵירֹ֥ם אָנֹ֖כִי וָאֵחָבֵֽא׃",
          "וַיֹּ֕אמֶר מִ֚י הִגִּ֣יד לְךָ֔ כִּ֥י עֵירֹ֖ם אָ֑תָּה הֲמִן־הָעֵ֗ץ אֲשֶׁ֧ר צִוִּיתִ֛יךָ לְבִלְתִּ֥י אֲכׇל־מִמֶּ֖נּוּ אָכָֽלְתָּ׃",
          "וַיֹּ֖אמֶר הָֽאָדָ֑ם הָֽאִשָּׁה֙ אֲשֶׁ֣ר נָתַ֣תָּה עִמָּדִ֔י הִ֛וא נָֽתְנָה־לִּ֥י מִן־הָעֵ֖ץ וָאֹכֵֽל׃",
          "וַיֹּ֨אמֶר יְהֹוָ֧ה אֱלֹהִ֛ים לָאִשָּׁ֖ה מַה־זֹּ֣את עָשִׂ֑ית וַתֹּ֙אמֶר֙ הָֽאִשָּׁ֔ה הַנָּחָ֥שׁ הִשִּׁיאַ֖נִי וָאֹכֵֽל׃",
          "וַיֹּ֩אמֶר֩ יְהֹוָ֨ה אֱלֹהִ֥ים&thinsp;׀&thinsp;אֶֽל־הַנָּחָשׁ֮ כִּ֣י עָשִׂ֣יתָ זֹּאת֒ אָר֤וּר אַתָּה֙ מִכׇּל־הַבְּהֵמָ֔ה וּמִכֹּ֖ל חַיַּ֣ת הַשָּׂדֶ֑ה עַל־גְּחֹנְךָ֣ תֵלֵ֔ךְ וְעָפָ֥ר תֹּאכַ֖ל כׇּל־יְמֵ֥י חַיֶּֽיךָ׃",
          "וְאֵיבָ֣ה&thinsp;׀ אָשִׁ֗ית בֵּֽינְךָ֙ וּבֵ֣ין הָֽאִשָּׁ֔ה וּבֵ֥ין זַרְעֲךָ֖ וּבֵ֣ין זַרְעָ֑הּ ה֚וּא יְשׁוּפְךָ֣ רֹ֔אשׁ וְאַתָּ֖ה תְּשׁוּפֶ֥נּוּ עָקֵֽב׃&nbsp;{ס}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
          "אֶֽל־הָאִשָּׁ֣ה אָמַ֗ר הַרְבָּ֤ה אַרְבֶּה֙ עִצְּבוֹנֵ֣ךְ וְהֵֽרֹנֵ֔ךְ בְּעֶ֖צֶב תֵּֽלְדִ֣י בָנִ֑ים וְאֶל־אִישֵׁךְ֙ תְּשׁ֣וּקָתֵ֔ךְ וְה֖וּא יִמְשׇׁל־בָּֽךְ׃&nbsp;{ס}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
          "וּלְאָדָ֣ם אָמַ֗ר כִּֽי־שָׁמַ֘עְתָּ֮ לְק֣וֹל אִשְׁתֶּ֒ךָ֒ וַתֹּ֙אכַל֙ מִן־הָעֵ֔ץ אֲשֶׁ֤ר צִוִּיתִ֙יךָ֙ לֵאמֹ֔ר לֹ֥א תֹאכַ֖ל מִמֶּ֑נּוּ אֲרוּרָ֤ה הָֽאֲדָמָה֙ בַּֽעֲבוּרֶ֔ךָ בְּעִצָּבוֹן֙ תֹּֽאכְלֶ֔נָּה כֹּ֖ל יְמֵ֥י חַיֶּֽיךָ׃",
          "וְק֥וֹץ וְדַרְדַּ֖ר תַּצְמִ֣יחַֽ לָ֑ךְ וְאָכַלְתָּ֖ אֶת־עֵ֥שֶׂב הַשָּׂדֶֽה׃",
          "בְּזֵעַ֤ת אַפֶּ֙יךָ֙ תֹּ֣אכַל לֶ֔חֶם עַ֤ד שֽׁוּבְךָ֙ אֶל־הָ֣אֲדָמָ֔ה כִּ֥י מִמֶּ֖נָּה לֻקָּ֑חְתָּ כִּֽי־עָפָ֣ר אַ֔תָּה וְאֶל־עָפָ֖ר תָּשֽׁוּב׃",
          "וַיִּקְרָ֧א הָֽאָדָ֛ם שֵׁ֥ם אִשְׁתּ֖וֹ חַוָּ֑ה כִּ֛י הִ֥וא הָֽיְתָ֖ה אֵ֥ם כׇּל־חָֽי׃",
          "וַיַּ֩עַשׂ֩ יְהֹוָ֨ה אֱלֹהִ֜ים לְאָדָ֧ם וּלְאִשְׁתּ֛וֹ כׇּתְנ֥וֹת ע֖וֹר וַיַּלְבִּשֵֽׁם׃&nbsp;{פ}"
        ],
        "en": [
          "And the Human gave names to all the cattle and to the birds of the sky and to all the wild beasts; but no fitting counterpart for a human being was found.",
          "So the ETERNAL God cast a deep sleep upon the Human; and, while he slept, [God] took one of his sides and closed up the flesh at that site.",
          "And the ETERNAL God fashioned the side that had been taken from the Human into a woman, bringing her to the Human.",
          "Then the Human said, “This one at last Is bone of my bones And flesh of my flesh. This one shall be called the Woman, For from the Man was she taken.”",
          "Hence a man leaves his father and mother and clings to his wife, so that they become one flesh.",
          "The two of them were naked, the Human and his wife, yet they felt no shame.",
          "Now the serpent was the shrewdest of all the wild beasts that the ETERNAL God had made. It said to the woman, “Did God really say: You shall not eat of any tree of the garden?”",
          "The woman replied to the serpent, “We may eat of the fruit of the other trees of the garden.",
          "It is only about fruit of the tree in the middle of the garden that God said: ‘You shall not eat of it or touch it, lest you die.’”",
          "And the serpent said to the woman, “You are not going to die,",
          "but God knows that as soon as you eat of it your eyes will be opened and you will be like divine beings who know good and bad.”",
          "When the woman saw that the tree was good for eating and a delight to the eyes, and that the tree was desirable as a source of wisdom, she took of its fruit and ate. She also gave some to her husband, and he ate.",
          "Then the eyes of both of them were opened and they perceived that they were naked; and they sewed together fig leaves and made themselves loincloths.",
          "They heard the sound of the ETERNAL God moving about in the garden at the breezy time of day; and the Human and his wife hid from the ETERNAL God among the trees of the garden.",
          "The ETERNAL God called out to the Human and said to him, “Where are you?”",
          "He replied, “I heard the sound of You in the garden, and I was afraid because I was naked, so I hid.”",
          "“Who told you that you were naked? Did you eat of the tree from which I had forbidden you to eat?”",
          "The Human said, “The woman You put at my side—she gave me of the tree, and I ate.”",
          "And the ETERNAL God said to the woman, “What is this you have done!” The woman replied, “The serpent duped me, and I ate.”",
          "Then the ETERNAL God said to the serpent, “Because you did this, More cursed shall you be Than all cattle And all the wild beasts: On your belly shall you crawl And dirt shall you eat All the days of your life.",
          "I will put enmity Between you and the woman, And between your offspring and hers; They shall strike at your head, And you shall strike at their heel.”",
          "And to the woman [God] said, “I will greatly expand Your toil—and your pregnancies; In hardship shall you bear children. Yet your urge shall be for your husband, And his will shall prevail over yours.”",
          "To Adam [God] said, “Because you did as your wife said and ate of the tree about which I commanded you, ‘You shall not eat of it,’ Cursed be the ground because of you; By toil shall you eat of it All the days of your life:",
          "Thorns and thistles shall it sprout for you. But your food shall be the grasses of the field;",
          "By the sweat of your brow Shall you get bread to eat, Until you return to the ground— For from it you were taken. For dust you are, And to dust you shall return.”",
          "The Human named his wife Eve, because she was the mother of all the living.",
          "And the ETERNAL God made garments of skins for Adam and his wife, and clothed them."
        ]
      },
      "rashi": {
        "ref": "Rashi on Genesis 2:20-3:21",
        "he": [
          "ולאדם לא מצא עזר. ויפל ה' אלהים תרדמה. כְּשֶׁהֱבִיאָן הֱבִיאָן לְפָנָיו כָּל מִין וָמִין זָכָר וּנְקֵבָה, אָמַר לְכֻלָּם יֵשׁ בֶּן זוּג וְלִי אֵין בֶּן זוּג, מִיָּד וַיַּפֵּל (בראשית רבה):",
          "מצלעותיו. מִסְּטָרָיו, כְּמוֹ וּלְצֶלַע הַמִּשְׁכָּן (שמות כ\"ו), זֶהוּ שֶׁאָמְרוּ שְׁנֵי פַרְצוּפִים נִבְרְאוּ (עירובין י\"ז):",
          "ויסגור. מְקוֹם הַחֲתָךְ:",
          "ויישן ויקח. שֶׁלֹּא יִרְאֶה חֲתִיכַת הַבָּשָׂר שֶׁמִּמֶּנוּ נִבְרֵאת וְתִתְבַּזֶּה עָלָיו:",
          "ויבן. כְּבִִנְיָן, רְחָבָה מִלְּמַטָּה וּקְצָרָה מִלְּמַעְלָה לְקַבֵּל הַוָּלָד כְּאוֹצָר שֶׁל חִטִּים, שֶׁהוּא רָחָב מִלְּמַטָה וְקָצָר מִלְּמַעְלָה שֶׁלֹּא יַכְבִּיד מַשָּׂאוֹ עַל קִירוֹתָיו:",
          "ויבן את הצלע לאשה. לִהְיוֹת אִשָּׁה, כְּמוֹ וַיַּעַשׂ אוֹתוֹ גִדְעוֹן לְאֵפוֹד (שופטים ח'), לִהְיוֹת אֵפוֹד:",
          "זאת הפעם. מְלַמֵּד שֶׁבָּא אָדָם עַל כָּל בְּהֵמָה וְחַיָּה, וְלֹא נִתְקָרְרָה דַעְתּוֹ בָּהֶם (יבמות ס\"ג):",
          "לזאת יקרא אשה כי מאיש וגו'. לָשׁוֹן נוֹפֵל עַל לָשׁוֹן מִכָּאן שֶׁנִּבְרָא הָעוֹלָם בִּלְשׁוֹן הַקֹּדֶשׁ (בראשית רבה):",
          "על כן יעזב איש. רוּחַ הַקֹּדֶשׁ אוֹמְרָה כֵן לֶאֱסֹר עַל בְּנֵי נֹחַ הָעֲרָיוֹת (סנהדרין נ\"ז):",
          "לבשר אחד. הַוָּלָד נוֹצָר עַל יְדֵי שְׁנֵיהֶם וְשָׁם נַעֲשֶׁה בְשָׂרָם אֶחָד (שם נ\"ח):",
          "ולא יתבוששו. שֶׁלֹּא הָיוּ יוֹדְעִים דֶרֶךְ צְנִיעוּת לְהַבְחִין בֵּין טוֹב לָרָע, וְאַעַ\"פִּ שֶׁנִּתְּנָה בוֹ דֵּעָה לִקְרוֹת לוֹ שֵׁמוֹת, לֹא נִתַּן בּוֹ יֵצֶר הָרָע עַד אָכְלוֹ מִן הָעֵץ וְנִכְנַס בּוֹ יֵצֶר הָרָע וְיָדַע מַה בֵּין טוֹב לָרָע (בראשית רבה):",
          "והנחש היה ערום. מָה עִנְיָן זֶה לְכָאן? הָיָה לוֹ לִסְמֹךְ וַיַּעַשׂ לְאָדָם וּלְאִשְׁתּוֹ כָּתְנוֹת עוֹר וַיַּלְבִּשֵׁם, אֶלָּא לִמֶּדְךָ מֵאֵיזוֹ עֵצָה קָפַץ הַנָּחַשׁ עֲלֵיהֶם, רָאָה אוֹתָם עֲרֻמִּים וְעוֹסְקִים בְּתַשְׁמִישׁ לְעֵין כֹּל וְנִתְאַוָּה לָהּ:",
          "ערום מכל. לְפִי עָרְמָתוֹ וּגְדֻלָּתוֹ הָיְתָה מַפָּלָתוֹ, עָרוּם מִכֹּל, אָרוּר מִכֹּל (בראשית רבה):",
          "אף כי אמר וגו'. שֶׁמָּא אָמַר לָכֶם לֹא תֹאכְלוּ מִכֹּל וְגוֹ', וְאַעַ\"פִּ שֶׁרָאָה אוֹתָם אוֹכְלִים מִשְּׁאָר פֵּרוֹת, הִרְבָּה עָלֶיהָ דְבָרִים כְּדֵי שֶׁתְּשִׁיבֶנּוּ וְיָבֹא לְדַבֵּר בְּאוֹתוֹ הָעֵץ:",
          "ולא תגעו בו. הוֹסִיפָה עַל הַצִּוּוּי, לְפִיכָךְ בָּאָה לִידֵי גֵרָעוֹן, הוּא שֶׁנֶּאֱמַר אַל תּוֹסְףְּ עַל דְּבָרָיו (משלי ל'):",
          "לא מות תמותון. דְּחָפָהּ עַד שֶׁנָּגְעָה בוֹ, אָמַר לָהּ כְּשֵׁם שֶׁאֵין מִיתָה בִנְגִיעָה, כָּךְ אֵין מִיתָה בַאֲכִילָה (בראשית רבה):",
          "כי ידע. כָּל אֻמָּן שׂוֹנֵא אֶת בְּנֵי אֻמָּנוּתוֹ, מִן הָעֵץ אָכַל וּבָרָא אֶת הָעוֹלָם (בראשית רבה):",
          "והייתם כאלהים. יוֹצְרֵי עוֹלָמוֹת (בראשית רבה):",
          "ותרא האשה. רָאֲתָה דְבָרָיו שֶׁל נָחָשׁ וְהֶנְאוּ לָהּ וְהֶאֱמִינַתּוּ (בראשית רבה):",
          "כי טוב העץ. לִהְיוֹת כֵּאלֹהִים:",
          "וכי תאוה הוא לעינים. כְּמוֹ שֶׁאָמַר לָהּ וְנִפְקְחוּ עֵינֵיכֶם:",
          "ונחמד להשכיל. כְּמוֹ שֶׁאָמַר לָהּ יוֹדְעֵי טוֹב וָרָע:",
          "ותתן גם לאישה. שֶׁלֹּא תָמוּת הִיא וְיִחְיֶה הוּא, וְיִשָּׂא אַחֶרֶת:",
          "גם. לְרַבּוֹת בְּהֵמָה וְחַיָּה:",
          "ותפקחנה וגו'. לְעִנְיַן הַחָכְמָה דִּבֵּר הַכָּתוּב וְלֹא לְעִנְיַן רְאִיָּה מַמָּשׁ, וְסוֹף הַמִּקְרָא מוֹכִיחַ:",
          "וידעו כי עירמים הם. אַף הַסּוּמָא יוֹדֵעַ כְּשֶׁהוּא עָרוּם, אֶלָּא מַהוּ וַיֵּדְעוּ כִּי עֵירֻמִּם הֵם? מִצְוָה אַחַת הָיְתָה בְיָדָם וְנִתְעַרְטְלוּ הֵימֶנָּה (בראשית רבה):",
          "עלה תאנה. הוּא הָעֵץ שֶׁאָכְלוּ מִמֶּנּוּ, בַּדָּבָר שֶׁנִּתְקַלְקְלוּ בּוֹ נִתַּקְּנוּ (סנהדרין ע'), אֲבָל שְׁאָר הָעֵצִים מְנָעוּם מִלִּטֹּל עַלֵּיהֶם. וּמִפְּנֵי מָה לֹא נִתְפַּרְסֵם הָעֵץ? שֶׁאֵין הַקָּבָּ\"ה חָפֵץ לְהוֹנוֹת בְּרִיָּה, שֶׁלֹּא יַכְלִימוּהָ וְיֹאמְרוּ זֶהוּ שֶׁלָּקָה הָעוֹלָם עַל יָדוֹ, מִדְרַשׁ רַבִּי תַנְחוּמָא:",
          "וישמעו. יֵשׁ מִדְרְשֵׁי אַגָּדָה רַבִּים וּכְבָר סִדְּרוּם רַבּוֹתֵינוּ עַל מְכוֹנָם בִּבְ\"רַ וּבִשְׁאָר מִדְרָשׁוֹת; וַאֲנִי לֹא בָאתִי אֶלָּא לִפְשׁוּטוֹ שֶׁל מִקְרָא וּלְאַגָּדָה הַמְיַשֶּׁבֶת דִּבְרֵי הַמִּקְרָא דָבָר דָּבוּר עַל אׇפְנָיו: וישמעו. מַה שָּׁמְעוּ? שָׁמְעוּ אֶת קוֹל הַקָּבָּ\"ה שֶׁהָיָה מִתְהַלֵּךְ בַּגַּן:",
          "לרוח היום. לְאוֹתוֹ רוּחַ שֶׁהַשֶּׁמֶשׁ בָּאָה לְשָׁם, וְזוֹ הִיא מַעֲרָבִית; שֶׁלִּפְנוֹת עֶרֶב חַמָּה בַּמַּעֲרָב, וְהֵם סָרְחוּ בָּעֲשִׂירִית (סנהדרין ל\"ח):",
          "איכה. יוֹדֵעַ הָיָה הֵיכָן הוּא אֶלָּא לִכָּנֵס עִמּוֹ בִּדְבָרִים, שֶׁלֹּא יְהֵא נִבְהָל לְהָשִׁיב אִם יַעֲנִישֵׁהוּ פִּתְאוֹם (בראשית רבה), וְכֵן בְּקַיִן אָמַר לוֹ אֵי הֶבֶל אָחִיךָ (בראשית ד), וְכֵן בְּבִלְעָם מִי הָאֲנָשִׁים הָאֵלֶּה עִמָּךְ (במדבר כ\"ב), לִכָּנֵס עִמָּהֶם בִּדְבָרִים, וְכֵן בְּחִזְקִיָּה בִּשְׁלוּחֵי מְרֹאדַךְ בַּלְאֲדָן:",
          "מי הגיד לך. מֵאַיִן לְךָ לָדַעַת מַה בֹּשֶׁת יֵשׁ בְּעוֹמֵד עָרֹם?",
          "המן העץ. בִּתְמִיהָ:",
          "אשר נתתה עמדי. כָּאן כָּפַר בַּטּוֹבָה (עבודה זרה ה):",
          "השיאני. הִטְעַנִי, כְּמוֹ אַל יַשִּׁיא אֶתְכֶם חִזְקִיָּהוּ (דברי הימים ב' ל\"ב):",
          "כי עשית זאת. מִכָּאן שֶׁאֵין מְהַפְּכִים בִּזְכוּתוֹ שֶׁל מֵסִית, שֶׁאִלּוּ שְׁאָלוֹ לָמָּה עָשִׂיתָ זֹאת? הָיָה לוֹ לְהָשִׁיב דִּבְרֵי הָרַב וְדִבְרֵי הַתַּלְמִיד דִּבְרֵי מִי שׁוֹמְעִין? (סנהדרין כ\"ט):",
          "מכל הבהמה ומכל חית השדה. אִם מִבְּהֵמָה נִתְקַלֵּל מֵחַיָּה לֹא כָּל שֶׁכֵּן, הֶעֱמִידוּ רַבּוֹתֵינוּ מִדְרָשׁ זֶה בְמַסֶּכֶת בְּכוֹרוֹת (דף ח') לְלַמֵּד שֶׁיְּמֵי עִבּוּרוֹ שֶׁל נָחָשׁ שֶׁבַע שָׁנִים:",
          "על גחונך תלך. רַגְלַיִם הָיוּ לוֹ וְנִקְצְצוּ:",
          "ואיבה אשית. אַתָּה לֹא נִתְכַּוַּנְתָּ אֶלָּא שֶׁיָּמוּת אָדָם כְּשֶׁיּאֹכַל הוּא תְּחִלָּה וְתִשָּׂא אֶת חַוָּה, וְלֹא בָאתָ לְדַבֵּר אֶל חַוָּה תְּחִלָּה אֶלָּא לְפִי שֶׁהַנָּשִׁים קַלּוֹת לְהִתְפַּתּוֹת וְיוֹדְעוֹת לְפַתּוֹת אֶת בַּעְלֵיהֶן, לְפִיכָךְ וְאֵיבָה אָשִׁית:",
          "ישופך. יְכַתֶּתְךָ (סוטה ט') כְּמוֹ וָאֶכֹּת אֹתוֹ (דברים ט), וְתַרְגּוּמוֹ וְשָׁפִית יָתֵי':",
          "ואתה תשופנו עקב. לֹא יְהֵא לְךָ קוֹמָה וְתִשְּׁכֶנּוּ בַּעֲקֵבוֹ, וְאַף מִשָּׁם תְּמִיתֶנּוּ, וּלְשׁוֹן תְּשׁוּפֶנּוּ כְּמוֹ נָשַׁף בָּהֶם (ישעיהו מ') כְּשֶׁהַנָּחָשׁ בָּא לִנְשֹׁך הוּא נוֹשֵׁף כְּמִין שְׁרִיקָה וּלְפִי שֶׁהַלָּשׁוֹן נוֹפֵל עַל הַלָּשָוֹן כְּתִיב לְשׁוֹן נְשִׁיפָה בִשְׁנֵיהֶם:",
          "עצבונך. זֶה צַעַר גִּדּוּל בָּנִים (עירובין ק'):",
          "והרנך. זֶה צַעַר הָעִבּוּר:",
          "בעצב תלדי בנים. זֶה צַעַר הַלֵּדָה:",
          "ואל אישך תשוקתך. לְתַשְׁמִישׁ, וְאַעַפִּ\"כֵּ אֵין לָךְ מֵצַח לְתָבְעוֹ בַּפֶּה, אֶלָּא הוּא יִמְשָׁל בָּךְ, הַכֹּל מִמֶּנּוּ וְלֹא מִמֵּךְ:",
          "תשוקתך. תַּאֲוָתֵךְ, כְּמוֹ נֶפֶשׁ שׁוֹקֵקָה (ישעיהו כ\"ט):",
          "ארורה האדמה בעבורך. מַעֲלָה לְךָ דְּבָרִים אֲרוּרִים, כְּגוֹן זְבוּבִים, פַּרְעוֹשִׁים וּנְמָלִים, מָשָׁל לְיוֹצֵא לְתַרְבּוּת רָעָה וְהַבְּרִיּוֹת מְקַלְּלוֹת שָׁדַיִם שֶׁיָּנַק מֵהֶם:",
          "וקוץ ודרדר תצמיח לך. הָאָרֶץ כְּשֶׁתִּזְרָעֶנָּה מִינֵי זְרָעִים, תַּצְמִיחַ קוֹץ וְדַרְדַּר קֻנְדָּס וְעַכָּבִיּוֹת, וְהֵן נֶאֱכָלִין עַל יְדֵי תִקּוּן (ביצה ל\"ד):",
          "ואכלת את עשב השדה. וּמַה קְּלָלָה הִיא זוֹ? וַהֲלֹא בַּבְּרָכָה נֶאֱמַר לוֹ הִנֵּה נָתַתִּי לָכֶם אֶת כָּל עֵשֶׂב זֹרֵעַ זֶרַע וְגוֹ? אֶלָּא מָה אָמוּר כָּאן בְּרֹאשׁ הָעִנְיָן אֲרוּרָה הָאֲדָמָה בַּעֲבוּרֶךָ בְּעִצָּבוֹן תֹּאכְלֶנָּה, וְאַחַר הָעִצָּבוֹן וְקוֹץ וְדַרְדַּר תַּצְמִיחַ לָךְ, כְּשֶׁתִּזְרָעֶנָּה קִטְנִית אוֹ יַרְקוֹת גִּנָּה הִיא תַצְמִיחַ לְךָ קוֹצִים וְדַרְדָּרִים וּשְׁאָר עִשְׂבֵי הַשָׂדֶה וְעַל כָּרְחֲךָ תֹּאכְלֵם:",
          "בזעת אפיך. לְאַחַר שֶׁתִּטְרַח בּוֹ הַרְבֵּה:",
          "ויקרא האדם. חָזַר הַכָּתוּב לְעִנְיָנוֹ הָרִאשׁוֹן וַיִּקְרָא הָאָדָם שֵׁמוֹת, וְלֹא הִפְסִיק אֶלָּא לְלַמֶּדְךָ שֶׁעַל יְדֵי קְרִיאַת שֵׁמוֹת נִזְדַּוְּגָה לוֹ חַוָּה, כְּמוֹ שֶׁכָּתוּב וּלְאָדָם לֹא מָצָא עֵזֶר כְּנֶגְדּוֹ, לְפִיכָךְ, וַיַּפֵּל תַּרְדֵּמָה, וְעַל יְדֵי שֶׁכָּתַב וַיִּהְיוּ עֲרוּמִּים, סָמַךְ לוֹ פָּרָשַׁת הַנָּחָשׁ, לְהוֹדִיעֲךְ שֶׁמִּתּוֹךְ שֶׁרָאָה עֶרְוָתָהּ וְרָאָה אוֹתָם עֲסוּקִים בְּתַשְׁמִישׁ נִתְאַוָּה לָהּ וּבָא עֲלֵיהֶם בְּמַחֲשָׁבָה וּבְמִרְמָה:",
          "חוה. נוֹפֵל עַל לְשׁוֹן חַיָּה, שֶׁמְּחַיָּה אֶת וַלְדוֹתֶיהָ, כַּאֲשֶׁר תֹּאמַר מֶה הֹוֶה לָאָדָם (קהלת ב'), בִּלְשׁוֹן הָיָה:",
          "כתנות עור. יֵשׁ דִּבְרֵי אַגָּדָה אוֹמְרִים חֲלָקִים כְּצִּפֹּרֶן הָיוּ מְדֻבָּקִים עַל עוֹרָן וְיֵ\"אֹ דָּבָר הַבָּא מִן הָעוֹר, כְּגוֹן צֶמֶר הָאַרְנָבִים שֶׁהוּא רַךְ וְחָם וְעָשָׂה לָהֶם כֻּתֳּנוֹת מִמֶּנּוּ:"
        ],
        "en": [
          "ואל אישך תשוקתך AND TO YOUR HUSBAND WILL BE YOUR DESIRE — for sexual relations. And, nonetheless, you will not have the temerity to proposition him with [your] mouth, but rather HE WILL RULE OVER YOU — everything will come from him and not from you."
        ]
      }
    },
    "haftarah": {
      "ref": "I Samuel 20:18-42",
      "link": "https://www.sefaria.org/I_Samuel_20%3A18-42"
    },
    "tehillim": {
      "day_of_month": 25,
      "ref": "Psalms 119:1-96",
      "link": "https://www.sefaria.org/Psalms_119%3A1-96",
      "chabad": "https://www.chabad.org/dailystudy/tehillim.asp?tdate=10/6/2026",
      "text": {
        "ref": "Psalms 119:1-96",
        "he": [
          "אַשְׁרֵ֥י תְמִֽימֵי־דָ֑רֶךְ הַ֝הֹלְכִ֗ים בְּתוֹרַ֥ת יְהֹוָֽה׃",
          "אַ֭שְׁרֵי נֹצְרֵ֥י עֵדֹתָ֗יו בְּכׇל־לֵ֥ב יִדְרְשֽׁוּהוּ׃",
          "אַ֭ף לֹא־פָעֲל֣וּ עַוְלָ֑ה בִּדְרָכָ֥יו הָלָֽכוּ׃",
          "אַ֭תָּה צִוִּ֥יתָה פִקֻּדֶ֗יךָ לִשְׁמֹ֥ר מְאֹֽד׃",
          "אַ֭חֲלַי יִכֹּ֥נוּ דְרָכָ֗י לִשְׁמֹ֥ר חֻקֶּֽיךָ׃",
          "אָ֥ז לֹא־אֵב֑וֹשׁ בְּ֝הַבִּיטִ֗י אֶל־כׇּל־מִצְוֺתֶֽיךָ׃",
          "א֭וֹדְךָ בְּיֹ֣שֶׁר לֵבָ֑ב בְּ֝לׇמְדִ֗י מִשְׁפְּטֵ֥י צִדְקֶֽךָ׃",
          "אֶת־חֻקֶּ֥יךָ אֶשְׁמֹ֑ר אַֽל־תַּעַזְבֵ֥נִי עַד־מְאֹֽד׃&nbsp;{פ}",
          "בַּמֶּ֣ה יְזַכֶּה־נַּ֭עַר אֶת־אׇרְח֑וֹ לִ֝שְׁמֹ֗ר כִּדְבָרֶֽךָ׃",
          "בְּכׇל־לִבִּ֥י דְרַשְׁתִּ֑יךָ אַל־תַּ֝שְׁגֵּ֗נִי מִמִּצְוֺתֶֽיךָ׃",
          "בְּ֭לִבִּי צָפַ֣נְתִּי אִמְרָתֶ֑ךָ לְ֝מַ֗עַן לֹ֣א אֶחֱטָא־לָֽךְ׃",
          "בָּר֖וּךְ אַתָּ֥ה יְהֹוָ֗ה לַמְּדֵ֥נִי חֻקֶּֽיךָ׃",
          "בִּשְׂפָתַ֥י סִפַּ֑רְתִּי כֹּ֝֗ל מִשְׁפְּטֵי־פִֽיךָ׃",
          "בְּדֶ֖רֶךְ עֵדְוֺתֶ֥יךָ שַּׂ֗שְׂתִּי כְּעַ֣ל כׇּל־הֽוֹן׃",
          "בְּפִקּוּדֶ֥יךָ אָשִׂ֑יחָה וְ֝אַבִּ֗יטָה אֹֽרְחֹתֶֽיךָ׃",
          "בְּחֻקֹּתֶ֥יךָ אֶֽשְׁתַּעֲשָׁ֑ע לֹ֖א אֶשְׁכַּ֣ח דְּבָרֶֽךָ׃&nbsp;{פ}",
          "גְּמֹ֖ל עַל־עַבְדְּךָ֥ אֶחְיֶ֗ה וְאֶשְׁמְרָ֥ה דְבָרֶֽךָ׃",
          "גַּל־עֵינַ֥י וְאַבִּ֑יטָה נִ֝פְלָא֗וֹת מִתּוֹרָתֶֽךָ׃",
          "גֵּ֣ר אָנֹכִ֣י בָאָ֑רֶץ אַל־תַּסְתֵּ֥ר מִ֝מֶּ֗נִּי מִצְוֺתֶֽיךָ׃",
          "גָּרְסָ֣ה נַפְשִׁ֣י לְתַאֲבָ֑ה אֶֽל־מִשְׁפָּטֶ֥יךָ בְכׇל־עֵֽת׃",
          "גָּ֭עַרְתָּ זֵדִ֣ים אֲרוּרִ֑ים הַ֝שֹּׁגִ֗ים מִמִּצְוֺתֶֽיךָ׃",
          "גַּ֣ל מֵ֭עָלַי חֶרְפָּ֣ה וָב֑וּז כִּ֖י עֵדֹתֶ֣יךָ נָצָֽרְתִּי׃",
          "גַּ֤ם יָשְׁב֣וּ שָׂ֭רִים בִּ֣י נִדְבָּ֑רוּ עַ֝בְדְּךָ֗ יָשִׂ֥יחַ בְּחֻקֶּֽיךָ׃",
          "גַּֽם־עֵ֭דֹתֶיךָ שַׁעֲשֻׁעָ֗י אַנְשֵׁ֥י עֲצָתִֽי׃&nbsp;{פ}",
          "דָּבְקָ֣ה לֶעָפָ֣ר נַפְשִׁ֑י חַ֝יֵּ֗נִי כִּדְבָרֶֽךָ׃",
          "דְּרָכַ֣י סִ֭פַּרְתִּי וַֽתַּעֲנֵ֗נִי לַמְּדֵ֥נִי חֻקֶּֽיךָ׃",
          "דֶּרֶךְ־פִּקּוּדֶ֥יךָ הֲבִינֵ֑נִי וְ֝אָשִׂ֗יחָה בְּנִפְלְאוֹתֶֽיךָ׃",
          "דָּלְפָ֣ה נַ֭פְשִׁי מִתּוּגָ֑ה קַ֝יְּמֵ֗נִי כִּדְבָרֶֽךָ׃",
          "דֶּֽרֶךְ־שֶׁ֭קֶר הָסֵ֣ר מִמֶּ֑נִּי וְֽתוֹרָתְךָ֥ חׇנֵּֽנִי׃",
          "דֶּֽרֶךְ־אֱמוּנָ֥ה בָחָ֑רְתִּי מִשְׁפָּטֶ֥יךָ שִׁוִּֽיתִי׃",
          "דָּבַ֥קְתִּי בְעֵדְוֺתֶ֑יךָ יְ֝הֹוָ֗ה אַל־תְּבִישֵֽׁנִי׃",
          "דֶּֽרֶךְ־מִצְוֺתֶ֥יךָ אָר֑וּץ כִּ֖י תַרְחִ֣יב לִבִּֽי׃&nbsp;{פ}",
          "הוֹרֵ֣נִי יְ֭הֹוָה דֶּ֥רֶךְ חֻקֶּ֗יךָ וְאֶצְּרֶ֥נָּה עֵֽקֶב׃",
          "הֲ֭בִינֵנִי וְאֶצְּרָ֥ה תוֹרָתֶ֗ךָ וְאֶשְׁמְרֶ֥נָּה בְכׇל־לֵֽב׃",
          "הַ֭דְרִיכֵנִי בִּנְתִ֣יב מִצְוֺתֶ֑יךָ כִּי־ב֥וֹ חָפָֽצְתִּי׃",
          "הַט־לִ֭בִּי אֶל־עֵדְוֺתֶ֗יךָ וְאַ֣ל אֶל־בָּֽצַע׃",
          "הַעֲבֵ֣ר עֵ֭ינַי מֵרְא֣וֹת שָׁ֑וְא בִּדְרָכֶ֥ךָ חַיֵּֽנִי׃",
          "הָקֵ֣ם לְ֭עַבְדְּךָ אִמְרָתֶ֑ךָ אֲ֝שֶׁ֗ר לְיִרְאָתֶֽךָ׃",
          "הַעֲבֵ֣ר חֶ֭רְפָּתִי אֲשֶׁ֣ר יָגֹ֑רְתִּי כִּ֖י מִשְׁפָּטֶ֣יךָ טוֹבִֽים׃",
          "הִ֭נֵּה תָּאַ֣בְתִּי לְפִקֻּדֶ֑יךָ בְּצִדְקָתְךָ֥ חַיֵּֽנִי׃&nbsp;{פ}",
          "וִיבֹאֻ֣נִי חֲסָדֶ֣ךָ יְהֹוָ֑ה תְּ֝שׁ֥וּעָתְךָ֗ כְּאִמְרָתֶֽךָ׃",
          "וְאֶעֱנֶ֣ה חֹרְפִ֣י דָבָ֑ר כִּֽי־בָ֝טַ֗חְתִּי בִּדְבָרֶֽךָ׃",
          "וְֽאַל־תַּצֵּ֬ל מִפִּ֣י דְבַר־אֱמֶ֣ת עַד־מְאֹ֑ד כִּ֖י לְמִשְׁפָּטֶ֣ךָ יִחָֽלְתִּי׃",
          "וְאֶשְׁמְרָ֖ה תוֹרָתְךָ֥ תָמִ֗יד לְעוֹלָ֥ם וָעֶֽד׃",
          "וְאֶתְהַלְּכָ֥ה בָרְחָבָ֑ה כִּ֖י פִקֻּדֶ֣יךָ דָרָֽשְׁתִּי׃",
          "וַאֲדַבְּרָ֣ה בְ֭עֵדֹתֶיךָ נֶ֥גֶד מְלָכִ֗ים וְלֹ֣א אֵבֽוֹשׁ׃",
          "וְאֶשְׁתַּעֲשַׁ֥ע בְּמִצְוֺתֶ֗יךָ אֲשֶׁ֣ר אָהָֽבְתִּי׃",
          "וְאֶשָּֽׂא־כַפַּ֗י אֶֽל־מִ֭צְוֺתֶיךָ אֲשֶׁ֥ר אָהָ֗בְתִּי וְאָשִׂ֥יחָה בְחֻקֶּֽיךָ׃&nbsp;{פ}",
          "זְכֹר־דָּבָ֥ר לְעַבְדֶּ֑ךָ עַ֝֗ל אֲשֶׁ֣ר יִחַלְתָּֽנִי׃",
          "זֹ֣את נֶחָמָתִ֣י בְעׇנְיִ֑י כִּ֖י אִמְרָתְךָ֣ חִיָּֽתְנִי׃",
          "זֵ֭דִים הֱלִיצֻ֣נִי עַד־מְאֹ֑ד מִ֝תּ֥וֹרָתְךָ֗ לֹ֣א נָטִֽיתִי׃",
          "זָ֘כַ֤רְתִּי מִשְׁפָּטֶ֖יךָ מֵעוֹלָ֥ם&thinsp;׀&thinsp;יְהֹוָ֗ה וָאֶתְנֶחָֽם׃",
          "זַלְעָפָ֣ה אֲ֭חָזַתְנִי מֵרְשָׁעִ֑ים עֹ֝זְבֵ֗י תּוֹרָתֶֽךָ׃",
          "זְ֭מִרוֹת הָיוּ־לִ֥י חֻקֶּ֗יךָ בְּבֵ֣ית מְגוּרָֽי׃",
          "זָ֘כַ֤רְתִּי בַלַּ֣יְלָה שִׁמְךָ֣ יְהֹוָ֑ה וָ֝אֶשְׁמְרָ֗ה תּוֹרָתֶֽךָ׃",
          "זֹ֥את הָיְתָה־לִּ֑י כִּ֖י פִקֻּדֶ֣יךָ נָצָֽרְתִּי׃&nbsp;{פ}",
          "חֶלְקִ֖י יְהֹוָ֥ה אָמַ֗רְתִּי לִשְׁמֹ֥ר דְּבָרֶֽיךָ׃",
          "חִלִּ֣יתִי פָנֶ֣יךָ בְכׇל־לֵ֑ב חׇ֝נֵּ֗נִי כְּאִמְרָתֶֽךָ׃",
          "חִשַּׁ֥בְתִּי דְרָכָ֑י וָאָשִׁ֥יבָה רַ֝גְלַ֗י אֶל־עֵדֹתֶֽיךָ׃",
          "חַ֭שְׁתִּי וְלֹ֣א הִתְמַהְמָ֑הְתִּי לִ֝שְׁמֹ֗ר מִצְוֺתֶֽיךָ׃",
          "חֶבְלֵ֣י רְשָׁעִ֣ים עִוְּדֻ֑נִי תּ֥֝וֹרָתְךָ֗ לֹ֣א שָׁכָֽחְתִּי׃",
          "חֲצֽוֹת־לַ֗יְלָה אָ֭קוּם לְהוֹד֣וֹת לָ֑ךְ עַ֝֗ל מִשְׁפְּטֵ֥י צִדְקֶֽךָ׃",
          "חָבֵ֣ר אָ֭נִי לְכׇל־אֲשֶׁ֣ר יְרֵא֑וּךָ וּ֝לְשֹׁמְרֵ֗י פִּקּוּדֶֽיךָ׃",
          "חַסְדְּךָ֣ יְ֭הֹוָה מָלְאָ֥ה הָאָ֗רֶץ חֻקֶּ֥יךָ לַמְּדֵֽנִי׃&nbsp;{פ}",
          "ט֭וֹב עָשִׂ֣יתָ עִֽם־עַבְדְּךָ֑ יְ֝הֹוָ֗ה כִּדְבָרֶֽךָ׃",
          "ט֤וּב טַ֣עַם וָדַ֣עַת לַמְּדֵ֑נִי כִּ֖י בְמִצְוֺתֶ֣יךָ הֶאֱמָֽנְתִּי׃",
          "טֶ֣רֶם אֶ֭עֱנֶה אֲנִ֣י שֹׁגֵ֑ג וְ֝עַתָּ֗ה אִמְרָתְךָ֥ שָׁמָֽרְתִּי׃",
          "טוֹב־אַתָּ֥ה וּמֵטִ֗יב לַמְּדֵ֥נִי חֻקֶּֽיךָ׃",
          "טָפְל֬וּ עָלַ֣י שֶׁ֣קֶר זֵדִ֑ים אֲ֝נִ֗י בְּכׇל־לֵ֤ב&thinsp;׀ אֶצֹּ֬ר פִּקּוּדֶֽיךָ׃",
          "טָפַ֣שׁ כַּחֵ֣לֶב לִבָּ֑ם אֲ֝נִ֗י תּוֹרָתְךָ֥ שִׁעֲשָֽׁעְתִּי׃",
          "טֽוֹב־לִ֥י כִי־עֻנֵּ֑יתִי לְ֝מַ֗עַן אֶלְמַ֥ד חֻקֶּֽיךָ׃",
          "טֽוֹב־לִ֥י תוֹרַת־פִּ֑יךָ מֵ֝אַלְפֵ֗י זָהָ֥ב וָכָֽסֶף׃&nbsp;{פ}",
          "יָדֶ֣יךָ עָ֭שׂוּנִי וַֽיְכוֹנְנ֑וּנִי הֲ֝בִינֵ֗נִי וְאֶלְמְדָ֥ה מִצְוֺתֶֽיךָ׃",
          "יְ֭רֵאֶיךָ יִרְא֣וּנִי וְיִשְׂמָ֑חוּ כִּ֖י לִדְבָרְךָ֣ יִחָֽלְתִּי׃",
          "יָדַ֣עְתִּי יְ֭הֹוָה כִּי־צֶ֣דֶק מִשְׁפָּטֶ֑יךָ וֶ֝אֱמוּנָ֗ה עִנִּיתָֽנִי׃",
          "יְהִי־נָ֣א חַסְדְּךָ֣ לְנַחֲמֵ֑נִי כְּאִמְרָתְךָ֥ לְעַבְדֶּֽךָ׃",
          "יְבֹא֣וּנִי רַחֲמֶ֣יךָ וְאֶחְיֶ֑ה כִּי־ת֥֝וֹרָתְךָ֗ שַׁעֲשֻׁעָֽי׃",
          "יֵבֹ֣שׁוּ זֵ֭דִים כִּי־שֶׁ֣קֶר עִוְּת֑וּנִי אֲ֝נִ֗י אָשִׂ֥יחַ בְּפִקּוּדֶֽיךָ׃",
          "יָשׁ֣וּבוּ לִ֣י יְרֵאֶ֑יךָ (וידעו) [וְ֝יֹדְעֵ֗י] עֵדֹתֶֽיךָ׃",
          "יְהִי־לִבִּ֣י תָמִ֣ים בְּחֻקֶּ֑יךָ לְ֝מַ֗עַן לֹ֣א אֵבֽוֹשׁ׃&nbsp;{פ}",
          "כָּלְתָ֣ה לִתְשׁוּעָתְךָ֣ נַפְשִׁ֑י לִדְבָרְךָ֥ יִחָֽלְתִּי׃",
          "כָּל֣וּ עֵ֭ינַי לְאִמְרָתֶ֑ךָ לֵ֝אמֹ֗ר מָתַ֥י תְּֽנַחֲמֵֽנִי׃",
          "כִּֽי־הָ֭יִיתִי כְּנֹ֣אד בְּקִיט֑וֹר חֻ֝קֶּ֗יךָ לֹ֣א שָׁכָֽחְתִּי׃",
          "כַּמָּ֥ה יְמֵֽי־עַבְדֶּ֑ךָ מָתַ֬י תַּעֲשֶׂ֖ה בְרֹדְפַ֣י מִשְׁפָּֽט׃",
          "כָּרוּ־לִ֣י זֵדִ֣ים שִׁיח֑וֹת אֲ֝שֶׁ֗ר לֹ֣א כְתוֹרָתֶֽךָ׃",
          "כׇּל־מִצְוֺתֶ֥יךָ אֱמוּנָ֑ה שֶׁ֖קֶר רְדָפ֣וּנִי עׇזְרֵֽנִי׃",
          "כִּ֭מְעַט כִּלּ֣וּנִי בָאָ֑רֶץ וַ֝אֲנִ֗י לֹא־עָזַ֥בְתִּי פִקֻּדֶֽיךָ׃",
          "כְּחַסְדְּךָ֥ חַיֵּ֑נִי וְ֝אֶשְׁמְרָ֗ה עֵד֥וּת פִּֽיךָ׃&nbsp;{פ}",
          "לְעוֹלָ֥ם יְהֹוָ֑ה דְּ֝בָרְךָ֗ נִצָּ֥ב בַּשָּׁמָֽיִם׃",
          "לְדֹ֣ר וָ֭דֹר אֱמוּנָתֶ֑ךָ כּוֹנַ֥נְתָּֽ אֶ֝֗רֶץ וַֽתַּעֲמֹֽד׃",
          "לְֽ֭מִשְׁפָּטֶיךָ עָמְד֣וּ הַיּ֑וֹם כִּ֖י הַכֹּ֣ל עֲבָדֶֽיךָ׃",
          "לוּלֵ֣י ת֭וֹרָתְךָ שַׁעֲשֻׁעָ֑י אָ֝֗ז אָבַ֥דְתִּי בְעׇנְיִֽי׃",
          "לְ֭עוֹלָם לֹא־אֶשְׁכַּ֣ח פִּקּוּדֶ֑יךָ כִּ֥י בָ֝֗ם חִיִּיתָֽנִי׃",
          "לְֽךָ־אֲ֭נִי הוֹשִׁיעֵ֑נִי כִּ֖י פִקּוּדֶ֣יךָ דָרָֽשְׁתִּי׃",
          "לִ֤י קִוּ֣וּ רְשָׁעִ֣ים לְאַבְּדֵ֑נִי עֵ֝דֹתֶ֗יךָ אֶתְבּוֹנָֽן׃",
          "לְֽכׇל־תִּ֭כְלָה רָאִ֣יתִי קֵ֑ץ רְחָבָ֖ה מִצְוָתְךָ֣ מְאֹֽד׃&nbsp;{פ}"
        ],
        "en": [
          "א Happy are those whose way is blameless, who follow GOD’s teaching.",
          "Happy are those who observe God’s decrees, who turn to the divine wholeheartedly.",
          "They have done no wrong, but have followed God’s ways.",
          "You have commanded that Your precepts be kept diligently.",
          "Would that my ways were firm in keeping Your laws;",
          "then I would not be ashamed when I regard all Your commandments.",
          "I will praise You with a sincere heart as I learn Your just rules.",
          "I will keep Your laws; do not utterly forsake me.",
          "ב How can youths keep their way pure?— by holding to Your word.",
          "I have turned to You with all my heart; do not let me stray from Your commandments.",
          "In my heart I treasure Your promise; therefore I do not sin against You.",
          "Blessed are You, O ETERNAL One; train me in Your laws.",
          "With my lips I rehearse all the rules You proclaimed.",
          "I rejoice over the way of Your decrees as over all riches.",
          "I study Your precepts; I regard Your ways;",
          "I take delight in Your laws; I will not neglect Your word.",
          "ג Deal kindly with Your servant, that I may live to keep Your word.",
          "Open my eyes, that I may perceive the wonders of Your teaching.",
          "I am only a sojourner in the land; do not hide Your commandments from me.",
          "My soul is consumed with longing for Your rules at all times.",
          "You blast the accursed insolent ones who stray from Your commandments.",
          "Take away from me taunt and abuse, because I observe Your decrees.",
          "Though princes meet and speak against me, Your servant studies Your laws.",
          "For Your decrees are my delight, my intimate companions.",
          "ד My soul clings to the dust; revive me in accordance with Your word.",
          "I have declared my way, and You have answered me; train me in Your laws.",
          "Make me understand the way of Your precepts, that I may study Your wondrous acts.",
          "I am racked with grief; sustain me in accordance with Your word.",
          "Remove all false ways from me; favor me with Your teaching.",
          "I have chosen the way of faithfulness; I have set Your rules before me.",
          "I cling to Your decrees; O ETERNAL One, do not put me to shame.",
          "I eagerly pursue Your commandments, for You broaden my understanding.",
          "ה Teach me, O ETERNAL One, the way of Your laws; I will observe them to the utmost.",
          "Give me understanding, that I may observe Your teaching and keep it wholeheartedly.",
          "Lead me in the path of Your commandments, for that is my concern.",
          "Turn my heart to Your decrees and not to love of gain.",
          "Avert my eyes from seeing falsehood; by Your ways preserve me.",
          "Fulfill Your promise to Your servant, which is for those who worship You.",
          "Remove the taunt that I dread, for Your rules are good.",
          "See, I have longed for Your precepts; by Your righteousness preserve me.",
          "ו May Your steadfast love reach me, O ETERNAL One, Your deliverance, as You have promised.",
          "I shall have an answer for those who taunt me, for I have put my trust in Your word.",
          "Do not utterly take the truth away from my mouth, for I have put my hope in Your rules.",
          "I will always obey Your teaching, forever and ever.",
          "I will walk about at ease, for I have turned to Your precepts.",
          "I will speak of Your decrees, and not be ashamed in the presence of kings.",
          "I will delight in Your commandments, which I love.",
          "I reach out for Your commandments, which I love; I study Your laws.",
          "ז Remember Your word to Your servant through which You have given me hope.",
          "This is my comfort in my affliction, that Your promise has preserved me.",
          "Though the arrogant have cruelly mocked me, I have not swerved from Your teaching.",
          "I remember Your rules of old, O ETERNAL One, and find comfort in them.",
          "I am seized with rage because of the wicked who forsake Your teaching.",
          "Your laws are a source of strength to me wherever I may dwell.",
          "I remember Your name at night, O ETERNAL One, and obey Your teaching.",
          "This has been my lot, for I have observed Your precepts.",
          "ח GOD is my portion; I have resolved to keep Your words.",
          "I have implored You with all my heart; have mercy on me, in accordance with Your promise.",
          "I have considered my ways, and have turned back to Your decrees.",
          "I have hurried and not delayed to keep Your commandments.",
          "Though the bonds of the wicked are coiled round me, I have not neglected Your teaching.",
          "I arise at midnight to praise You for Your just rules.",
          "I am a companion to all who fear You, to those who keep Your precepts.",
          "Your steadfast love, O ETERNAL One, fills the earth; teach me Your laws.",
          "ט You have treated Your servant well, according to Your word, O ETERNAL One.",
          "Teach me good sense and knowledge, for I have put my trust in Your commandments.",
          "Before I was humbled I went astray, but now I keep Your word.",
          "You are good and beneficent; teach me Your laws.",
          "Though the arrogant have accused me falsely, I observe Your precepts wholeheartedly.",
          "Their minds are thick like fat; as for me, Your teaching is my delight.",
          "It was good for me that I was humbled, so that I might learn Your laws.",
          "I prefer the teaching You proclaimed to thousands of gold and silver pieces.",
          "י Your hands made me and fashioned me; give me understanding that I may learn Your commandments.",
          "Those who fear You will see me and rejoice, for I have put my hope in Your word.",
          "I know, O ETERNAL One, that Your rulings are just; rightly have You humbled me.",
          "May Your steadfast love comfort me in accordance with Your promise to Your servant.",
          "May Your mercy reach me, that I might live, for Your teaching is my delight.",
          "Let the insolent be dismayed, for they have wronged me without cause; I will study Your precepts.",
          "May those who fear You, those who know Your decrees, turn again to me.",
          "May I wholeheartedly follow Your laws so that I do not come to grief.",
          "כ I long for Your deliverance; I hope for Your word.",
          "My eyes pine away for Your promise; I say, “When will You comfort me?”",
          "Though I have become like a water-skin dried in smoke, I have not neglected Your laws.",
          "How long has Your servant to live? when will You bring my persecutors to judgment?",
          "The insolent have dug pits for me, flouting Your teaching.",
          "All Your commandments are enduring; I am persecuted without cause; help me!",
          "Though they almost wiped me off the earth, I did not abandon Your precepts.",
          "As befits Your steadfast love, preserve me, so that I may keep the decree You proclaimed.",
          "ל GOD exists forever; Your word stands firm in heaven.",
          "Your faithfulness is for all generations; You have established the earth, and it stands.",
          "They stand this day to [carry out] Your rulings, for all are Your servants.",
          "Were not Your teaching my delight I would have perished in my affliction.",
          "I will never neglect Your precepts, for You have preserved my life through them.",
          "I am Yours; save me! For I have turned to Your precepts.",
          "The wicked hope to destroy me, but I ponder Your decrees.",
          "I have seen that all things have their limit, but Your commandment is broad beyond measure."
        ]
      }
    },
    "tanya": {
      "ref": "Tanya, Part IV; Iggeret HaKodesh 25:1",
      "display": "25 Tishrei",
      "link": "https://www.sefaria.org/Tanya%2C_Part_IV%3B_Iggeret_HaKodesh_25%3A1",
      "chabad": "https://www.chabad.org/dailystudy/tanya.asp?tdate=10/6/2026",
      "text": {
        "ref": "Tanya, Part IV; Iggeret HaKodesh 25:1",
        "he": [
          "לְהָבִין אִמְרֵי בִינָה, מַה שֶּׁכָּתוּב בַּסֵּפֶר הַנִּקְרָא ״צַוָּואַת רִיבָ״שׁ״, הֲגַם שֶׁבֶּאֱמֶת אֵינָהּ צַוָּואָתוֹ כְּלָל, וְלֹא צִיוָּה כְּלָל לִפְנֵי פְטִירָתוֹ, רַק הֵם לִקּוּטֵי אִמְרוֹתָיו הַטְּהוֹרוֹת, שֶׁלִּקְּטוּ לְקוּטֵי בָּתַר לְקוּטֵי, וְלֹא יָדְעוּ לְכַוֵּין הַלָּשׁוֹן עַל מַתְכּוּנְתּוֹ, אַךְ הַמְכֻוָּון – הוּא אֱמֶת לַאֲמִיתּוֹ."
        ],
        "en": [
          "TWENTY-FIVE. “To comprehend the words of understanding” stated in the sacred book called Tzavaat Harivash—[though in fact it is not at all his testament, and he did not ordain anything before his passing; they are mere gleanings of his pure sayings that were gathered, “gleanings upon gleanings,” and (the compilers) did not know how to determine the phraseology exactly in its proper fashion. The connotation, however, is absolutely true.]"
        ]
      }
    },
    "rambam": {
      "three_perakim": {
        "ref": "Mishneh Torah, Damages to Property 12-14",
        "display": "Damages to Property 12-14",
        "link": "https://www.sefaria.org/Mishneh_Torah%2C_Damages_to_Property_12-14"
      },
      "one_perek": {
        "ref": "Mishneh Torah, Levirate Marriage and Release 2",
        "display": "Levirate Marriage and Release 2",
        "link": "https://www.sefaria.org/Mishneh_Torah%2C_Levirate_Marriage_and_Release_2",
        "text": {
          "ref": "Mishneh Torah, Levirate Marriage and Release 2",
          "he": [
            "מִדִּבְרֵי סוֹפְרִים שֶׁלֹּא יָבֹא הַיָּבָם עַל יְבִמְתּוֹ עַד שֶׁיְּקַדֵּשׁ אוֹתָהּ בִּפְנֵי שְׁנֵי עֵדִים בִּפְרוּטָה אוֹ בִּשְׁוֵה פְּרוּטָה וְזֶהוּ הַנִּקְרָא מַאֲמָר. וְאֵין הַמַּאֲמָר קוֹנֶה בַּיְבָמָה קִנְיָן גָּמוּר כְּמוֹ הַבִּיאָה. וְהָעוֹשֶׂה מַאֲמָר בִּיבִמְתּוֹ שֶׁלֹּא מִדַּעְתָּהּ לֹא עָשָׂה כְּלוּם שֶׁאֵין הָאִשָּׁה מִתְקַדֶּשֶׁת אֶלָּא לִרְצוֹנָהּ. וּקְטַנָּה מִן הָאֵרוּסִין אֵין עוֹשִׂין בָּהּ מַאֲמָר אֶלָּא מִדַּעַת אָבִיהָ:",
            "וּכְשֵׁם שֶׁהוּא מְקַדֵּשׁ אֶת יְבִמְתּוֹ כָּךְ הוּא מְבָרֵךְ בִּרְכַּת נִשּׂוּאִין בַּעֲשָׂרָה וְכוֹתֵב כְּתֻבָּה כְּדִין כָּל נוֹשֵׂא אִשָּׁה. הַבָּא עַל יְבִמְתּוֹ וְלֹא עָשָׂה בָּהּ מַאֲמָר קָנָה קִנְיָן גָּמוּר וְאֵינוֹ צָרִיךְ לַחֲזֹר וּלְקַדֵּשׁ אַחַר הַבְּעִילָה. וּמַכִּין אוֹתוֹ מַכַּת מַרְדּוּת. וְכוֹתֵב לָהּ כְּתֻבָּה:",
            "הַבָּא עַל יְבִמְתּוֹ בֵּין בְּשׁוֹגֵג בֵּין בְּמֵזִיד בֵּין בְּאֹנֶס בֵּין בְּרָצוֹן. בֵּין שֶׁהָיָה הוּא מֵזִיד וְהִיא שׁוֹגֶגֶת אוֹ אֲנוּסָה. בֵּין שֶׁהָיְתָה הִיא מְזִידָה וְהוּא שׁוֹגֵג אוֹ אָנוּס. בֵּין שֶׁהָיְתָה יְשֵׁנָה בֵּין שֶׁהָיְתָה עֵרָה (בֵּין שֶׁבָּא עָלֶיהָ כְּדַרְכָּהּ בֵּין שֶׁלֹּא כְּדַרְכָּהּ). אֶחָד הַמְעָרֶה וְאֶחָד הַגּוֹמֵר קָנָה:",
            "בַּמֶּה דְּבָרִים אֲמוּרִים שֶׁנִּתְכַּוֵּן לִבְעל אֲבָל (אִם נָפַל מִן הַגַּג וְנִתְקַע בָּהּ אוֹ) שֶׁבָּא עָלֶיהָ שִׁכּוֹר שֶׁאֵינוֹ מַכִּיר כְּלוּם אוֹ יָשֵׁן לֹא קָנָה. נִתְכַּוֵּן לְדָבָר אַחֵר וְהֵטִיחַ בִּיבִמְתּוֹ לֹא קָנָה. לְהָטִיחַ בִּבְהֵמָה וְהֵטִיחַ בִּיבִמְתּוֹ קָנָה שֶׁהֲרֵי נִתְכַּוִּן לְשׁוּם בְּעִילָה מִכָּל מָקוֹם:",
            "יְבָמָה שֶׁנִּתְיַבְּמָה וְאָמְרָה בְּתוֹךְ שְׁלֹשִׁים יוֹם לֹא נִבְעַלְתִּי וְאַף עַל פִּי שֶׁהוּא אוֹמֵר בָּעַלְתִּי וְגֵרְשָׁהּ כּוֹפִין אוֹתוֹ שֶׁיַּחֲלֹץ הוֹאִיל וְקִדֵּם וְגֵרְשָׁהּ בְּגֵט. וְאִם עֲדַיִן לֹא גֵּרֵשׁ כּוֹפִין אוֹתוֹ שֶׁיִּבְעל אוֹ יַחֲלֹץ וְיוֹצִיא בְּגֵט. גֵּרְשָׁהּ לְאַחַר שְׁלֹשִׁים יוֹם וְהִיא אוֹמֶרֶת לֹא נִבְעַלְתִּי מְבַקְּשִׁים מִמֶּנּוּ שֶׁיַּחֲלֹץ לָהּ. וְאִם הָיָה מוֹדֶה שֶׁלֹּא בָּעַל כּוֹפִין אוֹתוֹ לַחֲלֹץ. הִיא אוֹמֶרֶת נִבְעַלְתִּי וְהוּא אוֹמֵר לֹא בָּעַלְתִּי אֵינָהּ צְרִיכָה חֲלִיצָה שֶׁאֵין זֶה נֶאֱמָן לְאָסְרָהּ עַל כָּל אָדָם אַחַר שֶׁכְּנָסָהּ:",
            "מִי שֶׁמֵּת וְהִנִּיחַ אַחִים רַבִּים מִצְוָה עַל הַגָּדוֹל לְיַבֵּם אוֹ לַחֲלֹץ שֶׁנֶּאֱמַר (דברים כה ו) ״וְהָיָה הַבְּכוֹר אֲשֶׁר תֵּלֵד״‎‎. מִפִּי הַשְּׁמוּעָה לָמְדוּ שֶׁאֵינוֹ מְדַבֵּר אֶלָּא בִּבְכוֹר שֶׁבָּאַחִין כְּלוֹמַר גְּדוֹל הָאַחִין יָקוּם עַל שֵׁם אָחִיו הַמֵּת. וְזֶה שֶׁנֶּאֱמַר אֲשֶׁר תֵּלֵד מַשְׁמָעוֹ אֲשֶׁר יָלְדָה הָאֵם וְאֵין מַשְׁמָעוֹ אֲשֶׁר תֵּלֵד הַיְבָמָה:",
            "לֹא רָצָה הַגָּדוֹל לְיַבֵּם מְחַזְּרִין עַל כָּל הָאַחִין. לֹא רָצוּ חוֹזְרִין אֵצֶל הַגָּדוֹל וְאוֹמְרִין עָלֶיךָ מִצְוָה אוֹ חֲלֹץ אוֹ יַבֵּם. וְאֵין כּוֹפִין אֶת הַיָּבָם לְיַבֵּם אֲבָל כּוֹפִין אוֹתוֹ לַחֲלֹץ:",
            "אָמַר הַגָּדוֹל הַמְתִּינוּ לִי עַד שֶׁיַּגְדִּיל הַקָּטָן אוֹ עַד שֶׁיָּבוֹא הַהוֹלֵךְ אוֹ עַד שֶׁיַּבְרִיא הַחֵרֵשׁ וְנִמָּלֵךְ בּוֹ וְאִם לֹא יִרְצֶה אֲנִי אֲיַבֵּם אוֹ אֲנִי אֶחְלֹץ אֵין שׁוֹמְעִין לוֹ. אֶלָּא אוֹמְרִין לוֹ עָלֶיךָ מִצְוָה אוֹ יַבֵּם אוֹ חֲלֹץ:",
            "וְכֵן אִם הָיָה הַגָּדוֹל בִּמְדִינָה אַחֶרֶת אֵין אָחִיו הַקָּטָן יָכוֹל לוֹמַר עַל אָחִי הַגָּדוֹל הִיא הַמִּצְוָה הַמְתִּינוּ לוֹ עַד שֶׁיָּבוֹא אֶלָּא אוֹמְרִין לְזֶה שֶׁהוּא כָּאן יַבֵּם אוֹ חֲלֹץ:",
            "יְבָמָה הָרְאוּיָה לְיִבּוּם שֶׁלֹּא רָצְתָה לְהִתְיַבֵּם דִּינָהּ כְּדִין מוֹרֶדֶת עַל בַּעְלָהּ וְכוֹפִין אֶת יְבָמָהּ לַחֲלֹץ לָהּ וְתֵצֵא בְּלֹא כְּתֻבָּה. וְאִם הִנִּיחַ אָחִיו נָשִׁים רַבּוֹת כָּל מִי שֶׁתְּבָעָהּ הַיָּבָם מֵהֶן לְיִבּוּם וְלֹא רָצְתָה הִיא הַמּוֹרֶדֶת וְחוֹלֵץ לָהּ וְתֵצֵא בְּלֹא כְּתֻבָּה. וּשְׁאָר צָרוֹתֶיהָ שֶׁלֹּא נִתְבְּעוּ נוֹטְלוֹת כְּתֻבָּתָן כִּשְׁאָר הָאַלְמָנוֹת:",
            "הָיוּ הַיְבָמִין רַבִּים וְתָבַע אוֹתָהּ הַגָּדוֹל לְיִבּוּם וְהִיא אֵינָהּ רוֹצָה בּוֹ וְרוֹצָה בְּאָחִיו אֵין שׁוֹמְעִין לָהּ, שֶׁמִּצְוָה בַּגָּדוֹל לְיַבֵּם:",
            "אָמַר הַגָּדוֹל אֵינִי רוֹצֶה לֹא לְיַבֵּם וְלֹא לַחֲלֹץ. הֲרֵי אַחַי לְפָנַיִךְ. וְתָבַע אוֹתָהּ אֶחָד מִן הָאַחִין לְיִבּוּם וְהִיא אֵינָהּ רוֹצָה בּוֹ וְרָצְתָה בְּאָח אַחֵר וְהוּא רוֹצֶה בָּהּ. אֵין זוֹ מוֹרֶדֶת מֵאַחַר שֶׁנִּסְתַּלֵּק הַגָּדוֹל שֶׁמִּצְוָה בּוֹ הֲרֵי כֻּלָּן שָׁוִין וְהוֹאִיל וְהִיא רוֹצָה בְּאֶחָד מֵהֶן וְהוּא רוֹצֶה בָּהּ הֲרֵי זֹאת לֹא מָרְדָה. וְלֹא עוֹד אֶלָּא אִם הָיָה אֶחָד מֵהֶן בִּמְדִינָה אַחֶרֶת וְאָמְרָה הֲרֵי אֲנִי מַמְתֶּנֶת אוֹתוֹ עַד שֶׁיָּבוֹא וִייַבֵּם אוֹתִי אֲבָל זֶה אֵינִי רוֹצָה בּוֹ אֵין זוֹ מוֹרֶדֶת. וְאוֹמְרִים לְזֶה שֶׁאֵינוֹ הַגָּדוֹל הַתּוֹבֵעַ אוֹתָהּ אִם תִּרְצֶה לַחֲלֹץ לָהּ וְלִתֵּן לָהּ כְּתֻבָּה חֲלֹץ. וְאִם לָאו הֲרֵי רָצְתָה שֶׁתֵּשֵׁב עַד שֶׁיָּבוֹא אָחִיךָ הוֹאִיל וְאֵין לְךָ דִּין קְדִימָה עָלָיו:",
            "בָּא זֶה שֶׁתָּלְתָה בּוֹ וְלֹא רָצָה בָּהּ. חוֹזְרִין אֵצֶל זֶה שֶׁתָּבַע אוֹתָהּ לְיַבֵּם וְהִיא אֵינָהּ רוֹצָה בּוֹ. וְאוֹמְרִין לָהּ אֵין כָּאן מִי שֶׁרָצָה לְיַבֵּם אֶלָּא זֶה וּמִצְוַת יִבּוּם קוֹדֶמֶת. אוֹ תִּתְיַבֵּם לוֹ אוֹ תֵּצֵא בְּלֹא כְּתֻבָּה כְּדִין כָּל מוֹרֶדֶת:",
            "כָּל יְבָמָה שֶׁאָמַרְנוּ שֶׁדִּינָהּ שֶׁתַּחֲלֹץ וְלֹא תִּתְיַבֵּם הֲרֵי זוֹ נוֹטֶלֶת כְּתֻבָּתָהּ אִם יֵשׁ לָהּ כְּתֻבָּה כִּשְׁאָר כָּל הָאַלְמָנוֹת. וְכֵן אִם הָיָה יְבָמָהּ מֻכֶּה שְׁחִין אוֹ שֶׁיֵּשׁ בּוֹ שְׁאָר מוּמֵי אֲנָשִׁים חוֹלֵץ לָהּ וְנוֹטֶלֶת כְּתֻבָּתָהּ. נוֹלְדוּ בָּהּ מוּמִין כְּשֶׁהִיא שׁוֹמֶרֶת יָבָם, נִסְתַּחֲפָה שָׂדֵהוּ. אִם לֹא רָצָה לְיַבֵּם יַחֲלֹץ וְיִתֵּן כְּתֻבָּה:",
            "יְבָמָה שֶׁנָּדְרָה הֲנָיָה מִיבָמָהּ בְּחַיֵּי בַּעְלָהּ. אוֹ שֶׁנָּדְרָה הֲנָיָה מִכָּל הַיְּהוּדִים. כּוֹפִין אוֹתוֹ שֶׁיַּחֲלֹץ לָהּ וְתִטּל כְּתֻבָּתָהּ. וְאִם נָדְרָה לְאַחַר מִיתַת בַּעְלָהּ מְבַקְּשִׁים מִמֶּנּוּ שֶׁיַּחֲלֹץ לָהּ וְאִם לֹא רָצָה הֲרֵי זוֹ מוֹרֶדֶת. וְכֵן אִם נִתְכַּוְּנָה בְּנִדְרָהּ אֲפִלּוּ בְּחַיֵּי בַּעְלָהּ כְּדֵי שֶׁלֹּא יְיַבֵּם אוֹתָהּ אֵין כּוֹפִין אוֹתוֹ לַחֲלֹץ אֶלָּא אִם כֵּן מָרְדָה וְתֵצֵא בְּלֹא כְּתֻבָּה:",
            "יְבָמָה שֶׁתְּבָעָהּ הַיָּבָם לַחֲלִיצָה וְהִיא אוֹמֶרֶת אֵינִי חוֹלֶצֶת וְלֹא נוֹטֶלֶת כְּתֻבָּה אֶלָּא אֵשֵׁב בְּבֵית בַּעְלִי וְכִשְׁאָר כָּל הָאַלְמָנוֹת אֵין שׁוֹמְעִין לָהּ. שֶׁהֲרֵי הִקְנוּ אוֹתָהּ לְזֶה מִן הַשָּׁמַיִם. רָצָה מְיַבֵּם רָצָה חוֹלֵץ וְנוֹתֵן כְּתֻבָּה. וְלֹא עוֹד אֶלָּא אֲפִלּוּ אָמְרָה אֲנִי נִזּוֹנֶת מִשֶּׁלִּי וְאֵשֵׁב עֲגוּנָה כָּל יְמֵי חַיַּי אֵין שׁוֹמְעִין לָהּ. שֶׁהֲרֵי הַיָּבָם אוֹמֵר לָהּ כָּל זְמַן שֶׁאַתְּ זְקוּקָה לִי אֵין נוֹתְנִין לִי אִשָּׁה אַחֶרֶת. וַאֲפִלּוּ הָיָה נָשׂוּי אֶפְשָׁר שֶׁיִּשָּׂא אִשָּׁה אַחֶרֶת אוֹ תִּהְיֶה לוֹ מְרִיבָה בְּתוֹךְ בֵּיתוֹ מִפְּנֵי הַיְבָמָה:",
            "יְבָמָה שֶׁלֹּא הָיָה לָהּ עַל בַּעְלָהּ כְּתֻבָּה מִפְּנֵי שֶׁהָיְתָה אֲסוּרָה עָלָיו וַהֲרֵי הִיא מֻתֶּרֶת לַיָּבָם כְּמוֹ שֶׁיִּתְבָּאֵר. אִם רָצָה הַיָּבָם לְיַבֵּם מְיַבֵּם וְאֵין לָהּ עָלָיו כְּתֻבָּה כְּדֶרֶךְ שֶׁלֹּא הָיָה לָהּ עַל בַּעְלָהּ. וְדִינָהּ עִם יְבָמָהּ בַּתּוֹסֶפֶת כְּמוֹ שֶׁהָיְתָה עִם בַּעְלָהּ. אֲבָל אִם לֹא כָּתַב לָהּ בַּעְלָהּ כְּתֻבָּה אוֹ שֶׁמָּכְרָה לוֹ כְּתֻבָּתָהּ אוֹ מָחֲלָה אוֹתָהּ צָרִיךְ הַיָּבָם לִכְתֹּב לָהּ כְּתֻבָּה כִּשְׁאָר הָאַלְמָנוֹת:",
            "הַיְבָמָה קֹדֶם שֶׁיָּבוֹא עָלֶיהָ יְבָמָהּ אוֹ קֹדֶם שֶׁיַּחֲלֹץ לָהּ הֲרֵי הִיא אֲסוּרָה לְהִנָּשֵׂא לְזָר שֶׁנֶּאֱמַר (דברים כה ה) ״לֹא תִהְיֶה אֵשֶׁת הַמֵּת הַחוּצָה לְאִישׁ זָר״‎‎. וְאִם נִשֵּׂאת לְאַחֵר וּבָעַל לוֹקֶה הוּא וְהִיא וּמוֹצִיאָהּ בְּגֵט. וַאֲפִלּוּ הָיוּ לוֹ כַּמָּה בָּנִים מִמֶּנָּה. וְנֶאֶסְרָה עָלָיו וְעַל יְבָמָהּ. וִיבָמָהּ חוֹלֵץ לָהּ וְאַחַר כָּךְ תִּהְיֶה מֻתֶּרֶת לַאֲחֵרִים:",
            "נִתְקַדְּשָׁה לְאַחֵר לֹא נֶאֶסְרָה עַל יְבָמָהּ אֶלָּא נוֹתֵן לָהּ הַזָּר שֶׁקִּדְּשָׁהּ גֵּט וִיבָמָהּ מְיַבֵּם אוֹ חוֹלֵץ. וְאִם הָיָה יְבָמָהּ כֹּהֵן שֶׁאֵינוֹ יָכוֹל לִשָּׂא גְּרוּשָׁה תֵּצֵא מִן הַזָּר בְּגֵט כְּדֵי שֶׁלֹּא יְהֵא הַחוֹטֵא נִשְׂכָּר. וְיַחֲלֹץ לָהּ יְבָמָהּ:",
            "חָזַר הַזָּר שֶׁגֵּרְשָׁהּ מִן הָאֵרוּסִין וּנְשָׂאָהּ אַחַר שֶׁחָלַץ לָהּ יְבָמָהּ אֵין מוֹצִיאִין אוֹתָהּ מִיָּדוֹ. אֲבָל אִם גֵּרְשָׁהּ מִן הַנִּשּׂוּאִין וְחָזַר וּנְשָׂאָהּ אַחַר שֶׁחָלְצָה מוֹצִיאִין אוֹתָהּ מִיָּדוֹ מִפְּנֵי שֶׁהִיא דּוֹמָה לְאֵשֶׁת אִישׁ שֶׁנִּשֵּׂאת וּבָא בַּעְלָהּ שֶׁהִיא אֲסוּרָה עַל זֶה וְעַל זֶה כְּמוֹ שֶׁבֵּאַרְנוּ. וְהַיְבָמָה שֶׁזִּנְּתָה וְהִיא זְקוּקָה לֹא נֶאֶסְרָה עַל יְבָמָהּ אֶלָּא רָצָה חוֹלֵץ רָצָה מְיַבֵּם:",
            "כָּל יְבָמָה שֶׁהִיא סָפֵק מִדִּבְרֵיהֶם אִם יֵשׁ עָלֶיהָ זִקַּת יָבָם אוֹ אֵין עָלֶיהָ זִקַּת יָבָם. כְּגוֹן יְבָמָה שֶׁיָּלְדָה וָלָד שֶׁלֹּא כָּלוּ לוֹ חֳדָשָׁיו וּמֵת בְּתוֹךְ שְׁלֹשִׁים יוֹם שֶׁדִּינָהּ שֶׁתַּחֲלֹץ מִסָּפֵק מִדִּבְרֵיהֶם כְּמוֹ שֶׁבֵּאַרְנוּ. אִם הָלְכָה וְנִתְקַדְּשָׁה לְאַחֵר קֹדֶם חֲלִיצָה חוֹלֵץ לָהּ יְבָמָהּ וְתֵשֵׁב עִם בַּעְלָהּ. וְאִם נִתְקַדְּשָׁה לְכֹהֵן שֶׁהוּא אָסוּר בַּחֲלוּצָה אֵינוֹ חוֹלֵץ לָהּ. שֶׁאֵין אוֹסְרִין עַל זֶה אִשְׁתּוֹ מִשּׁוּם סְפֵק דִּבְרֵיהֶן. גֵּרְשָׁהּ הַכֹּהֵן אוֹ מֵת הֲרֵי זוֹ חוֹלֶצֶת וְאַחַר כָּךְ מֻתֶּרֶת לַאֲחֵרִים לְכַתְּחִלָּה:"
          ],
          "en": [
            "It is a Rabbinic ordinance that a yavam should not enter into marital relations with his yevamah until he consecrates her in the presence of two witnesses, with a p'rutah or an article worth a p'rutah. This [act] is called a ma'amar. A ma'amar does not complete the acquisition of a yevamah, as will be explained. When [a yavam] performs a ma'amar with his yevamah without her knowledge, his deed is of no consequence. For a woman can be consecrated only willingly. When a minor is widowed after being merely consecrated, a ma'amar can be performed only with the consent of her father.",
            "Just as [the yavam] must consecrate his yevamah, so too, he should recite the marriage blessings in the presence of ten men and compose a ketubah (\"marriage contract\"), as is required of any man who marries a woman. When [a yavam] enters into marital relations with his yevamah without previously performing a ma'amar with her, he acquires her in a binding manner; he does not have to consecrate her after engaging in marital relations with her. He should be given stripes for rebellious conduct and should write a ketubah for her.",
            "When [a yavam] engages in marital relations with his yevamah, he acquires her [as his wife]. [This applies] regardless of whether he entered into these relations unintentionally or with a licentious intent, under duress or willingly, whether he acted with a licentious intent and she acted unintentionally or under duress, or she acted with a licentious intent and he acted unintentionally or under duress, whether she was asleep or awake, whether he performed vaginal or anal intercourse, whether he inserted merely the head of his penis or the entire organ.",
            "When does the above apply? When [the yavam] intends to perform a sexual act. If, however, he fell from the roof [with an erection] and [accidentally] inserted his organ into his yevamah, had relations with her when he was so intoxicated that he was not conscious of anything, or when he was asleep, he does not acquire her [as his wife]. If he intended to masturbate in a hole in the wall and unintentionally inserted his organ into his yevamah, he does not acquire her [as his wife]. If he intended to sodomize an animal and unintentionally inserted his organ into his yevamah, he does acquire her [as his wife].",
            "[The following rules apply when a yavam takes] his yevamah [home to] perform yibbum, and within 30 days she claims that they did not engage in sexual relations. [The yavam] claims that they did engage in relations and then divorces her. Since he already took the initiative and divorced her, we compel him to perform chalitzah with her. If he did not divorce her, we compel him to engage in relations with her, or to perform chalitzah and also to divorce her, giving her a get. If he divorced her after thirty days had passed, and she claims that they did not engage in sexual relations, we request that he perform chalitzah with her. If, however, he admits that he had not entered into relations with her, we compel him to perform chalitzah with her. If she claims that they engaged in sexual relations, and he denies engaging in relations, she is not required to engage in chalitzah, for his word is not accepted [when he desires] to cause her to be forbidden to all other men, once he brings her to his home as his wife.",
            "When a man dies [childless], and he is survived by many brothers, the mitzvah is incumbent on the eldest brother to perform either yibbum or chalitzah, as [implied by Deuteronomy 25:6]: \"The firstborn son whom she bears [will perpetuate the name of the deceased brother].\" The Oral Tradition interprets the verse as referring to the eldest of the surviving brothers, causing the verse to be rendered: \"The eldest brother will perpetuate the name of the deceased brother.\" The subject of the phrase \"whom she bears\" is the mother of the brothers and not the yevamah.",
            "If the eldest brother does not desire to perform yibbum, all the other brothers are given that option. If they also do not desire, we return to the eldest brother and tell him: \"The mitzvah is incumbent on you. Perform either yibbum or chalitzah.\" We do not compel the yavam to perform yibbum; we do, however, compel him to perform chalitzah.",
            "If the eldest brother says: \"Give me a respite until [a brother] who is a minor attains majority,\" \"... until [a brother] who is on a journey returns,\" or \"... until [a brother] who has [temporarily] lost his powers of speech and hearing recovers; if he refuses, I will perform yibbum or chalitzah\" - his request is not accepted. He is told: \"The mitzvah is incumbent on you. Perform either yibbum or chalitzah.\"",
            "Similarly, if the eldest brother is in another country, [the obligation is transferred to his younger brother]. The younger brother does not have the option of saying: \"The mitzvah is incumbent on my older brother. Wait until he comes.\" Instead, we tell the brother that is present: \"Perform either yibbum or chalitzah.\"",
            "The laws pertaining to a yevamah who is fit to perform yibbum and refuses to do so are the same as those governing a woman who rebels against her husband. We compel her yavam to perform chalitzah with her, and she forfeits [the money due her by virtue of her] marriage contract. When the deceased is survived by many wives, the one that the yavam asks to perform yibbum and refuses is considered to have \"rebelled.\" He should perform chalitzah with her, and she forfeits [the money due her by virtue of her] marriage contract. The other wives who were not asked [to perform yibbum] receive [the money due them by virtue of their] marriage contracts, as other widows do.",
            "If [the deceased was survived by] many [brothers], and the eldest brother states that he wants to perform yibbum with [one of the deceased's wives], [she is under obligation to him]. Even if she does not desire [to marry] him, but is willing to marry one of his brothers, her desire is not considered. For the mitzvah is that the eldest brother perform yibbum.",
            "[The following rules apply when] the eldest brother says: \"I do not want to perform either yibbum or chalitzah. Behold, my brother is present.\" If one of the brothers asks her to perform yibbum, and she does not desire [to marry] him, but she does desire [to marry] another brother, and he desires [to marry] her, she is not considered to have \"rebelled.\" Once the eldest brother upon whom the mitzvah is incumbent demurs, all the brothers are equal. Since she desires [to marry] one of [the brothers], and he desires [to marry] her, she is not considered to have \"rebelled.\" Moreover, if one of the brothers was in another country, and the woman says: \"I would prefer to wait for him to come and perform yibbum with me. I do not want [to marry] this one,\" she is not considered to have \"rebelled.\" [Since] the brother who asks [to marry her] is not the eldest, we tell him: \"If you desire to perform chalitzah and pay her [the money due her by virtue of her] marriage contract, you may. If not, she wants to wait until your brother comes. Since you do not have a prior claim, [she is granted that prerogative].",
            "If the brother [whom the yevamah desired to marry] returned and did not desire [to marry] her, we turn again to the brother who desired to perform yibbum, but was not desired by the woman. We tell the woman: \"There is no one who desires to perform yibbum with you except this one, and the mitzvah of yibbum is given priority. Either perform yibbum with this one, or leave without receiving [the money due because of your] marriage contract, as is the law with regard to all women who rebel.\"",
            "Whenever the law is that a woman should perform chalitzah and not yibbum, as we have mentioned, if she is entitled to receive [the money due her by virtue of] her marriage contract, she may collect that money in the same way as other widows. Similarly, if the yavam was a leper or he has other blemishes [for which] men [are required to divorce], he must perform chalitzah for her, and she is entitled to receive [the money due her by virtue of] her marriage contract. If a yevamah suffered blemishes while she was waiting for yibbum, it is the yavam's lack of fortune. If he does not desire to perform yibbum, he must perform chalitzah and give her [the money due her by virtue of] her marriage contract.",
            "When, during her [first] husband's lifetime, a yevamah takes a vow prohibiting her from deriving benefit from her yavam, or from all Jews, [her yavam] should be compelled to perform chalitzah for her, and she is entitled to collect [the money due by virtue of] her marriage contract. If she takes such a vow after her [first] husband's death, we request [her yavam] to perform chalitzah for her. If he does not desire to do so, she is considered to have \"rebelled.\" Similarly, even if she took such a vow in her husband's lifetime, if her intent was that he should not perform yibbum with her, he is not compelled to perform chalitzah, unless she [accepts the status of] one who rebels and forfeits [payment of] her marriage contract.",
            "No heed is paid to the words of a yevamah, when her yavam asks her to perform chalitzah, and she says: \"I do not want to perform chalitzah, nor do I want to collect [the money due me by virtue of my] marriage contract. Instead, I will remain in my husband's house like other widows.\" For she was given over to [the yavam] from heaven, and the choice [is his whether] to perform yibbum or to perform chalitzah and pay her [the money due her by virtue of her] marriage contract. Moreover, even if she says \"I will provide for my sustenance from my own means, and I will remain without a husband for the rest of my life,\" her words are not heeded. For the yavam will tell her: \"As long as you are under obligation to me, no one else will want to marry me.\" Even if he is already married [this argument still holds weight], for it is possible for him [to desire] to marry another wife, or that [his obligation to] the yevamah will cause strife within his marriage.",
            "[The following rules apply when] a yevamah had no right to the privileges of a marriage contract from her [deceased] husband, because she was forbidden to him, but she is permitted to marry the yavam, as will be explained. If the yavam desires to perform yibbum, he may. He is not obligated to the woman [for the privileges of her] marriage contract, just as her [previous] husband was not. The laws regarding the yavam's obligation for the additional amount to be paid the woman are the same as those that applied with regard to her husband. If, however, a husband did not write his wife a marriage contract, or she sold him or waived to him the rights to her marriage contract, the yavam is obligated to write a new marriage contract for her as he would be required for another widow.",
            "Before the yavam performs yibbum or chalitzah with the yevamah, she is forbidden to marry another man, as [Deuteronomy 25:5] states: \"the wife of the deceased should not be allowed to [marry] an outsider.\" If she marries another person, and they engage in sexual relations, they are both punished by lashes, and he must divorce her with a get. [This applies] even if she has borne him several children. She is forbidden to him and to her yavam. Her yavam should perform chalitzah with her; this causes her to be permitted to marry other men.",
            "If she was consecrated by another man, she does not become forbidden to her yavam. Instead, the man who consecrated her should divorce her, and her yavam may perform either yibbum or chalitzah. If her yavam was a priest who is forbidden to marry a divorcee, she should be divorced by the man who consecrated her, so that the sinner should not benefit, and her yavam should perform chalitzah with her.",
            "If the man who consecrated [the yevamah] and then divorced her, marries her [after] her yavam performs chalitzah with her, they are not forced to separate. If, by contrast, a man divorced [a yevamah] after being married to her and then remarried her again, the couple are forced to separate. For this resembles the case of a married woman who [thought that her husband had died and] remarried, who is forbidden to both her first and second husbands, as has been explained. A yevamah who engages in licentious sexual relations does not become forbidden to her yavam. If he desires, he may perform chalitzah; if he desires, he may perform yibbum.",
            "[The following rules apply to] any yevamah concerning whom there is a question according to Rabbinic law whether or not she is under obligation to a yavam - e.g., a yevamah bore a child who died within thirty days, after a pregnancy that was not full term. In this instance, she is required by Rabbinic law to perform chalitzah, because of the doubt [that exists whether the birth was viable], as explained above. If such a woman was consecrated by another man before performing chalitzah, her yavam should perform chalitzah with her, and she may remain married to her husband. If she was consecrated by a priest - who is forbidden to be married to a woman who performed chalitzah - [her yavam] should not perform chalitzah for her. [This leniency was instituted] since we do not cause a man's wife to be forbidden because of a Rabbinic decree instituted on account of doubt. If the priest divorces [the woman] or dies, she should perform chalitzah. Afterwards, she is permitted, a priori, to marry other men."
          ]
        }
      },
      "chabad": "https://www.chabad.org/dailystudy/rambam.asp?tdate=10/6/2026"
    },
    "hayom_yom": {
      "ref": "Hayom Yom, Tishrei 25",
      "link": "https://www.sefaria.org/Hayom_Yom%2C_Tishrei_25",
      "chabad": "https://www.chabad.org/dailystudy/hayomyom.asp?tdate=10/6/2026",
      "text": null
    },
    "daf_yomi": {
      "ref": "Bekhorot 18",
      "display": "Bekhorot 18",
      "link": "https://www.sefaria.org/Bekhorot_18"
    }
  },
  "hebrew": {
    "hd": 25,
    "hm": "Tishrei",
    "hy": 5787,
    "hebrew": "כ״ה בְּתִשְׁרֵי תשפ״ז",
    "events": [
      "Parashat Bereshit"
    ]
  },
  "errors": [
    "hayom yom text: HTTPError: HTTP Error 404: Not Found (use the chabad link)"
  ]
}
;
