#!/usr/bin/env python3
"""Build the Desktop app's copies of the bundled Hebrew fonts.

Repackages each fonts/*.ttf below as WOFF 1.0 (each table zlib-compressed;
the font data itself is unchanged) and writes hooks/font-metrics.ts with the
glyph advances the sidebar wraps Hebrew lines by. Stdlib only. Run it again
if a .ttf changes:

    python3 scripts/make-woff.py
"""
import os
import struct
import zlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# The setting's key for each font, and its file under fonts/.
FONTS = [("shlomo", "Shlomo"), ("frank", "FrankRuhlLibre-Regular")]
METRICS = os.path.join(ROOT, "hooks", "font-metrics.ts")


def tables(data):
    num = struct.unpack(">H", data[4:6])[0]
    out = []
    for i in range(num):
        tag, checksum, off, length = struct.unpack(">4sIII", data[12 + 16 * i: 28 + 16 * i])
        out.append((tag, checksum, off, length))
    return out


def make_woff(data):
    flavor = data[0:4]
    tabs = sorted(tables(data), key=lambda t: t[0])
    header_len = 44 + 20 * len(tabs)
    entries, blobs, off = [], [], header_len
    for tag, checksum, toff, length in tabs:
        raw = data[toff: toff + length]
        comp = zlib.compress(raw, 9)
        if len(comp) >= length:
            comp = raw
        entries.append(struct.pack(">4sIIII", tag, off, len(comp), length, checksum))
        pad = (4 - len(comp) % 4) % 4
        blobs.append(comp + b"\0" * pad)
        off += len(comp) + pad
    total_sfnt = 12 + 16 * len(tabs) + sum((t[3] + 3) & ~3 for t in tabs)
    head = struct.pack(">4s4sIHHIHHIIIII", b"wOFF", flavor, off, len(tabs), 0,
                       total_sfnt, 1, 0, 0, 0, 0, 0, 0)
    return head + b"".join(entries) + b"".join(blobs)


def metrics(data):
    t = {tag: (off, length) for tag, _, off, length in tables(data)}
    upem = struct.unpack(">H", data[t[b"head"][0] + 18: t[b"head"][0] + 20])[0]
    hhea = t[b"hhea"][0]
    n_hmetrics = struct.unpack(">H", data[hhea + 34: hhea + 36])[0]
    hmtx = t[b"hmtx"][0]
    advances = [struct.unpack(">H", data[hmtx + 4 * i: hmtx + 4 * i + 2])[0] for i in range(n_hmetrics)]
    adv = lambda g: advances[min(g, n_hmetrics - 1)]
    # cmap: the first format 4 subtable (BMP)
    cmap = t[b"cmap"][0]
    n = struct.unpack(">H", data[cmap + 2: cmap + 4])[0]
    sub = None
    for i in range(n):
        pid, eid, o = struct.unpack(">HHI", data[cmap + 4 + 8 * i: cmap + 12 + 8 * i])
        if struct.unpack(">H", data[cmap + o: cmap + o + 2])[0] == 4:
            sub = cmap + o
            break
    seg2 = struct.unpack(">H", data[sub + 6: sub + 8])[0]
    ends = sub + 14
    starts = ends + seg2 + 2
    deltas = starts + seg2
    ranges = deltas + seg2

    def glyph(cp):
        for i in range(seg2 // 2):
            end = struct.unpack(">H", data[ends + 2 * i: ends + 2 * i + 2])[0]
            if cp > end:
                continue
            start = struct.unpack(">H", data[starts + 2 * i: starts + 2 * i + 2])[0]
            if cp < start:
                return 0
            delta = struct.unpack(">h", data[deltas + 2 * i: deltas + 2 * i + 2])[0]
            ro = struct.unpack(">H", data[ranges + 2 * i: ranges + 2 * i + 2])[0]
            if ro == 0:
                return (cp + delta) & 0xFFFF
            at = ranges + 2 * i + ro + 2 * (cp - start)
            g = struct.unpack(">H", data[at: at + 2])[0]
            return (g + delta) & 0xFFFF if g else 0
        return 0

    cps = list(range(0x05D0, 0x05EB)) + [0x05BE, 0x05C3, 0x05F3, 0x05F4] + list(range(0x20, 0x7F))
    out = {}
    for cp in cps:
        g = glyph(cp)
        if g:
            out[cp] = round(adv(g) / upem, 3)
    # Which nikkud the font draws (patah, qamats, sheva, dagesh, shin dot).
    missing = [hex(cp) for cp in (0x05B7, 0x05B8, 0x05B0, 0x05BC, 0x05C1) if not glyph(cp)]
    return out, missing


def main():
    tables_ts = []
    for key, name in FONTS:
        data = open(os.path.join(ROOT, "fonts", name + ".ttf"), "rb").read()
        woff = make_woff(data)
        open(os.path.join(ROOT, "fonts", name + ".woff"), "wb").write(woff)
        m, missing = metrics(data)
        body = ",\n".join(f"    0x{cp:04X}: {w}" for cp, w in sorted(m.items()))
        tables_ts.append(f"  {key}: {{\n{body},\n  }},")
        print(f"fonts/{name}.woff: {len(woff)} bytes ({len(data)} as TTF); "
              f"{len(m)} advances; nikkud missing: {missing or 'none'}")
    open(METRICS, "w").write(
        "// Generated by scripts/make-woff.py from fonts/*.ttf: each character's advance\n"
        "// width, in ems, per bundled font, for wrapping Hebrew in the Desktop app.\n"
        "// Combining marks take no width; a character missing here is taken as 0.55em.\n"
        "export const ADVANCE: Record<\"shlomo\" | \"frank\", Record<number, number>> = {\n"
        + "\n".join(tables_ts) + "\n};\n")


if __name__ == "__main__":
    main()
